image: Visual Studio 2019

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

#services:
#  - postgresql95

#before_build:
#  - SET PGUSER=postgres
#  - SET PGPASSWORD=Password12!
#  - PATH=C:\Program Files\PostgreSQL\9.5\bin\;%PATH%
#  - createdb rebus2_test
#  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.Oracle -c Release 
  - dotnet build Rebus.Oracle.Tests -c Release 

